### ISSUE TITLE
运行出现错误，显示Not Found

### ISSUE THREAD

**Issue by zby1234** [larvata/aidoru-online-rss-interop#1]
ubuntu14.04 npm 6.1.0 

运行后出现以下错误：
root@zby:/var/www/html/aidoru-online-rss-interop# npm start

> aidoru-online-rss-interop@0.1.0 start /var/www/html/aidoru-online-rss-interop
> node .

server listen at: http://localhost:3456
>>> Error: Not a feed
    at FeedParser.handleEnd (/var/www/html/aidoru-online-rss-interop/node_modules/feedparser/lib/feedparser/index.js:120:13)
    at emitNone (events.js:106:13)
    at SAXStream.emit (events.js:208:7)
    at SAXParser.SAXStream._parser.onend (/var/www/html/aidoru-online-rss-interop/node_modules/sax/lib/sax.js:190:10)
    at emit (/var/www/html/aidoru-online-rss-interop/node_modules/sax/lib/sax.js:624:35)
    at end (/var/www/html/aidoru-online-rss-interop/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.end (/var/www/html/aidoru-online-rss-interop/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/var/www/html/aidoru-online-rss-interop/node_modules/sax/lib/sax.js:248:18)
    at FeedParser._flush (/var/www/html/aidoru-online-rss-interop/node_modules/feedparser/lib/feedparser/index.js:1128:17)
    at FeedParser.<anonymous> (/var/www/html/aidoru-online-rss-interop/node_modules/readable-stream/lib/_stream_transform.js:138:49)
Sat Jun 23 2018 03:22:27 GMT+0000 (UTC) new xml has been updated.

**Comment by larvata** [comment]
config.js 里配置了你的账号了吗 ao 需要登录后才能获取列表

**Comment by zby1234** [comment]
配置账号了
我的配置：
module.exports = {
  AO_USERNAME: '我的账号',
  AO_PASSWORD: '我的秘密',
  AO_UFP: '',
  CHECK_INTERVAL: 300 * 1000,
  PORT: 3456,
};

登陆http://ip:3456显示 Not Found

**Comment by larvata** [comment]
用这个地址
http://localhost:3456/feeds.rss

**Comment by zby1234** [comment]
感谢指点
运行依旧有错误如图：http://t.cn/Rrx92AH
我登入了http://localhost:3456/feeds.rss
显示如图：http://t.cn/Rrx96hy

**Comment by larvata** [comment]
我这登录失败没做明确提示...
你应该是少了AO_UFP的值

在浏览器隐身窗口打开
https://aidoru-online.org/login.php
控制台输入
document.cookie.match(/ufp=(\S+)/)[1]
这样可以拿到 ufp 的值
这样应该就不报错了

ao 登录时需要这个值来确认请求是否来自他们网站

**Comment by zby1234** [comment]
谢谢你
问题解决了！
